version: '3.1'

services:
  postgres-dev:
    image: postgres:14-alpine
    container_name: toDoAPP-DEV-Postgres
    env_file: ./env/.postgres-dev.env
    volumes:
      - toDoDevDataPostgres:/var/lib/postgresql
    ports:
      - 5432:5432

  postgres-test:
    image: postgres:14-alpine
    container_name: toDoAPP-TEST-Postgres
    env_file: ./env/.postgres-test.env
    volumes:
      - toDoTestDataPostgres:/var/lib/postgresql
    ports:
      - 5433:5432

volumes:
  toDoDevDataPostgres:
  toDoTestDataPostgres: